name: finease
description: "A full stack mobile app to keep track of financial transactions"
publish_to: 'none'
version: 0.0.14

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  currency_picker: 2.0.20
  dynamic_color: 1.6.9
  flutter:
    sdk: flutter
  go_router: 13.0.1
  google_fonts: 6.1.0
  hive: 2.2.3
  http: 1.1.2
  intl: 0.19.0
  material_design_icons_flutter: 7.0.7296
  package_info_plus: 5.0.1
  path_provider: 2.1.2
  responsive_builder: 0.7.0
  share_plus: 7.0.2
  sqflite: 2.3.0
  xml: 6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
