name: fineas
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  get_it: 7.2.0
  flutter:
    sdk: flutter
  material_design_icons_flutter: 7.0.7296
  path_provider: 2.0.8
  responsive_builder: 0.4.1
  sqflite: ^2.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
