name: finease
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.3

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  currency_picker: 2.0.20
  dynamic_color: 1.6.5
  get_it: 7.2.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  go_router: 13.0.0
  google_fonts: 6.1.0
  material_design_icons_flutter: 7.0.7296
  package_info_plus: ^5.0.1
  path_provider: 2.0.8
  provider: 6.0.5
  responsive_builder: 0.4.1
  sqflite: ^2.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
