name: Release Android ARM64

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release Android ARM64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install and set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17.x'
          cache: gradle

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK for android-arm64
        run: flutter build apk --release

      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          fail_on_unmatched_files: true
          files: |
            build/app/outputs/apk/release/app-release.apk
          generate_release_notes: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
